db.host=${DB_HOST:localhost}
db.port=${DB_PORT:1433}
db.name=${DB_NAME:QuanLyThuVien}
db.user=${DB_USERNAME:sa}
db.password=${DB_PASSWORD:123456}
app.title=Library Management Desktop
# Mail (optional) - bật mail bằng cách đặt mail.enabled=true và khai báo thông tin bên dưới
mail.enabled=${MAIL_ENABLED:true}
mail.smtp.host=${MAIL_SMTP_HOST:smtp.gmail.com}
mail.smtp.port=${MAIL_SMTP_PORT:587}
mail.username=${MAIL_USERNAME:tuanta.25it@vku.udn.vn}
mail.password=${MAIL_PASSWORD:ylzz btmm nwrz gaeg}
mail.from=${MAIL_FROM:tuanta.25it@vku.udn.vn}
